FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH="/app"

#COPY . .
#COPY ./src /app/src

#EXPOSE 8020

#CMD ["python3", "src/main.py"]
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8020", "--reload"]
