
# Start up locally: docker-compose up --no-attach mongo
# View logs: docker-compose logs -f backbone-cis
# tail -f ${MONGO_VOLUME_PATH}/logs/mongod.log
# docker logs backbone-cis-mongo-1

services:

  # Backbone Data Service
  backbone-cis:
    image: wiseoneai/backbone-cis:${APP_VERSION}
    restart: always
    container_name: "backbone-cis"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    volumes:
      - ./.env:/app/.env
      - ./app.yml:/app/app.yml
      - ./agent-config.yml:/app/agent-config.yml
      - ./logging-config.yml:/app/logging-config.yml
    #command: "npm start"
    expose:
      - ${PORT}
    ports: 
      - ${PORT}:${PORT}