parameters:
  symbol:
    type: str
    description: "Symbol names are always uppercase, with the coin separated by a forward slash and the market: COIN/MARKET. For example: BTC/USDT Bitcoin to Tether, or LTC/BTC Litecoin to Bitcoin"
    required: true
  exchange:
    type: Literal['gateio', 'bianace', 'binancefutures', 'coinbase', 'kraken', 'bitstamp']
    required: false
    description: "The exchange you want to calculate the indicator from."
    default: gateio
  interval:
    name: Interval
    type: Literal['5m', '15m', '1h', '4h', '1d', '1w']
    required: true
    description: "The interval or time frame over which the indicator is calculated. It defines the granularity of the data points being analyzed."
